apiVersion: v1
kind: Namespace
metadata:
  name: konveyor-forklift
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forklift-console-plugin
  namespace: konveyor-forklift
  labels:
    app: forklift-console-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forklift-console-plugin
  template:
    metadata:
      labels:
        app: forklift-console-plugin
    spec:
      containers:
        - name: forklift-console-plugin
          image: quay.io/kubev2v/forklift-console-plugin:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
  namespace: konveyor-forklift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-console-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: console
    namespace: konveyor-forklift
---
apiVersion: v1
kind: Service
metadata:
  name: forklift-console-plugin
  namespace: konveyor-forklift
  labels:
    app: forklift-console-plugin
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: forklift-console-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: konveyor-forklift
spec:
  replicas: 1
  selector:
    matchLabels:
      name: console
  template:
    metadata:
      labels:
        name: console
    spec:
      serviceAccountName: console
      containers:
        - name: console
          image: quay.io/openshift/origin-console:4.19
          env:
            - name: BRIDGE_USER_AUTH
              value: disabled
            - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
              value: abcdef.0123456789abcdef
            - name: BRIDGE_PLUGINS
              value: forklift-console-plugin=http://forklift-console-plugin.konveyor-forklift.svc.cluster.local:8080
            - name: BRIDGE_PLUGIN_PROXY
              value: |
                {"services":[
                  {
                      "consoleAPIPath":"/api/proxy/plugin/forklift-console-plugin/forklift-inventory/",
                      "endpoint":"http://forklift-inventory.konveyor-forklift.svc.cluster.local:8080",
                      "authorize":true
                  },
                  {
                      "consoleAPIPath":"/api/proxy/plugin/forklift-console-plugin/must-gather-api/",
                      "endpoint":"http://must-gather-api.konveyor-forklift.svc.cluster.local:8080",
                      "authorize":true
                  }]}
---
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: konveyor-forklift
spec:
  ports:
    - name: api-http
      nodePort: 30080
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    name: console
  sessionAffinity: None
  type: NodePort
