export const setupHostsIntercepts = (sourceProviderType = 'vsphere') => {
  cy.intercept(
    'GET',
    `**/forklift-inventory/providers/${sourceProviderType}/test-source-uid-1/hosts?detail=4`,
    {
      statusCode: 200,
      body: [
        {
          id: 'test-host-1',
          parent: {
            kind: 'Cluster',
            id: 'test-cluster-1',
          },
          path: '/test/host/test-host-1.example.com/test-host-1.example.com',
          revision: 2,
          name: 'test-host-1.example.com',
          selfLink: `providers/${sourceProviderType}/test-source-uid-1/hosts/test-host-1`,
          cluster: 'test-cluster-1',
          status: 'green',
          inMaintenance: false,
          managementServerIp: '',
          thumbprint: '65:BA:1B:1F:2A:79:22:F6:47:26:07:8D:EB:97:72:2D:AF:39:CD:A8',
          timezone: 'UTC',
          cpuSockets: 1,
          cpuCores: 16,
          productName: 'VMware ESXi',
          productVersion: '7.0.0',
          apiVersion: '1',
          totalMemory: 274877906944,
          freeMemory: 137438953472,
          totalCpu: 38400,
          freeCpu: 19200,
          sslThumbprint: '65:BA:1B:1F:2A:79:22:F6:47:26:07:8D:EB:97:72:2D:AF:39:CD:A8',
          networks: ['test-network-1', 'test-network-2'],
          datastores: ['test-datastore-1', 'test-datastore-2'],
        },
        {
          id: 'test-host-2',
          parent: {
            kind: 'Cluster',
            id: 'test-cluster-2',
          },
          path: '/test/host/test-host-2.example.com/test-host-2.example.com',
          revision: 2,
          name: 'test-host-2.example.com',
          selfLink: `providers/${sourceProviderType}/test-source-uid-1/hosts/test-host-2`,
          cluster: 'test-cluster-2',
          status: 'green',
          inMaintenance: false,
          managementServerIp: '',
          thumbprint: '65:BA:1B:1F:2A:79:22:F6:47:26:07:8D:EB:97:72:2D:AF:39:CD:A9',
          timezone: 'UTC',
          cpuSockets: 2,
          cpuCores: 8,
          productName: 'VMware ESXi',
          productVersion: '7.0.0',
          apiVersion: '1',
          totalMemory: 137438953472,
          freeMemory: 68719476736,
          totalCpu: 25600,
          freeCpu: 12800,
          sslThumbprint: '65:BA:1B:1F:2A:79:22:F6:47:26:07:8D:EB:97:72:2D:AF:39:CD:A9',
          networks: ['test-network-1', 'test-network-3'],
          datastores: ['test-datastore-3', 'test-datastore-4'],
        },
        {
          id: 'test-host-3',
          parent: {
            kind: 'Cluster',
            id: 'test-cluster-3',
          },
          path: '/test/host/test-host-3.example.com/test-host-3.example.com',
          revision: 2,
          name: 'test-host-3.example.com',
          selfLink: `providers/${sourceProviderType}/test-source-uid-1/hosts/test-host-3`,
          cluster: 'test-cluster-3',
          status: 'yellow',
          inMaintenance: false,
          managementServerIp: '',
          thumbprint: '65:BA:1B:1F:2A:79:22:F6:47:26:07:8D:EB:97:72:2D:AF:39:CD:AA',
          timezone: 'UTC',
          cpuSockets: 1,
          cpuCores: 8,
          productName: 'VMware ESXi',
          productVersion: '6.7.0',
          apiVersion: '1',
          totalMemory: 68719476736,
          freeMemory: 34359738368,
          totalCpu: 19200,
          freeCpu: 9600,
          sslThumbprint: '65:BA:1B:1F:2A:79:22:F6:47:26:07:8D:EB:97:72:2D:AF:39:CD:AA',
          networks: ['test-network-2', 'test-network-3'],
          datastores: ['test-datastore-5', 'test-datastore-6'],
        },
      ],
    },
  ).as('getHosts');
};
