export const setupVirtualMachinesIntercepts = (sourceProviderType: string) => {
  cy.intercept(
    'GET',
    `**/forklift-inventory/providers/${sourceProviderType}/test-source-uid-1/vms?detail=4`,
    {
      statusCode: 200,
      body: [
        {
          id: 'test-vm-1',
          revision: 1,
          path: 'L0_Group_Test/test-vm-1',
          name: 'test-virtual-machine-1',
          selfLink: 'providers/test/test-vm-1',
          cluster: 'test-cluster-1',
          status: 'down',
          host: 'test-host-1',
          parent: {
            kind: 'Folder',
            id: 'test-folder-1',
          },
          isTemplate: false,
          revisionValidated: 1,
          nics: [
            {
              id: 'test-nic-1',
              name: 'nic1',
              interface: 'virtio',
              plugged: true,
              ipAddress: '',
              mac: '00:12:4a:16:37:2d',
            },
          ],
          diskAttachments: [
            {
              id: 'test-disk-1',
              interface: 'virtio_scsi',
              scsiReservation: false,
              disk: 'test-disk-1',
              bootable: true,
            },
          ],
          concerns: [],
          policyVersion: 6,
          guestName: 'Test Guest 1',
          cpuSockets: 2,
          cpuCores: 2,
          memory: 4294967296,
          osType: 'linux',
        },
        {
          id: 'test-vm-2',
          revision: 1,
          path: 'L0_Group_Test/test-vm-2',
          name: 'test-virtual-machine-2',
          selfLink: 'providers/test/test-vm-2',
          cluster: 'test-cluster-2',
          status: 'up',
          host: 'test-host-2',
          parent: {
            kind: 'Folder',
            id: 'test-folder-2',
          },
          isTemplate: false,
          revisionValidated: 1,
          nics: [
            {
              id: 'test-nic-2',
              name: 'nic1',
              interface: 'virtio',
              plugged: true,
              ipAddress: '',
              mac: '00:12:4a:16:37:2e',
            },
          ],
          diskAttachments: [
            {
              id: 'test-disk-2',
              interface: 'virtio_scsi',
              scsiReservation: false,
              disk: 'test-disk-2',
              bootable: true,
            },
          ],
          concerns: [],
          policyVersion: 6,
          guestName: 'Test Guest 2',
          cpuSockets: 4,
          cpuCores: 1,
          memory: 8589934592,
          osType: 'windows',
        },
        {
          id: 'test-vm-3',
          revision: 1,
          path: 'L0_Group_Test/test-vm-3',
          name: 'test-virtual-machine-3',
          selfLink: 'providers/test/test-vm-3',
          cluster: 'test-cluster-3',
          status: 'down',
          host: 'test-host-3',
          parent: {
            kind: 'Folder',
            id: 'test-folder-3',
          },
          isTemplate: false,
          revisionValidated: 1,
          nics: [
            {
              id: 'test-nic-3',
              name: 'nic1',
              interface: 'virtio',
              plugged: true,
              ipAddress: '',
              mac: '00:12:4a:16:37:2f',
            },
          ],
          diskAttachments: [
            {
              id: 'test-disk-3',
              interface: 'virtio_scsi',
              scsiReservation: false,
              disk: 'test-disk-3',
              bootable: true,
            },
          ],
          concerns: [],
          policyVersion: 6,
          guestName: 'Test Guest 3',
          cpuSockets: 1,
          cpuCores: 4,
          memory: 2147483648,
          osType: 'linux',
        },
      ],
    },
  ).as('getVirtualMachines');
};
