# Development container
FROM quay.io/fedora/fedora:37

# Setup env
# --------------------
USER root

# Install dev requirements
RUN dnf install openssh-clients openssh-server tmux vim git nodejs -y && \
    npm install -g yarn

# Add dev user ( pass: dev )
RUN useradd dev -p $(perl -e "print crypt('dev','salt')") && \
    ssh-keygen -A && \
    usermod -aG wheel dev && \
    echo '%wheel ALL=(ALL)       NOPASSWD: ALL' >> /etc/sudoers

# Git clone initial code
RUN git clone https://github.com/kubev2v/forklift-console-plugin.git /home/dev/forklift-console-plugin && \
    cd /home/dev/forklift-console-plugin/ && \
    yarn install && \
    chown -R dev:users /home/dev

# Start development sshd
# ----------------------
RUN printf "#!/bin/bash\n \
    echo 'Starting sshd'\n \
    echo '  user: dev'\n \
    echo '  pass: dev'\n \
    echo ''\n \
    /usr/sbin/sshd -e\n \
    sleep infinity\n" > /entrypoint.sh && \
    chmod ugo+rwx /entrypoint.sh

WORKDIR /home/dev/forklift-console-plugin
ENTRYPOINT ["/entrypoint.sh"]
