import type { CustomExtends } from 'eslint-define-config';

const disabledRules: CustomExtends = {
  rules: {
    '@cspell/spellchecker': 'off',
    '@typescript-eslint/consistent-return': 'off',
    '@typescript-eslint/explicit-member-accessibility': 'off',
    '@typescript-eslint/init-declarations': 'off',
    '@typescript-eslint/max-params': 'off',
    '@typescript-eslint/no-base-to-string': 'off',
    '@typescript-eslint/no-confusing-void-expression': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-floating-promises': 'off',
    '@typescript-eslint/no-for-in-array': 'off',
    '@typescript-eslint/no-shadow': 'off',
    '@typescript-eslint/no-unsafe-argument': 'off',
    '@typescript-eslint/no-unsafe-call': 'off',
    '@typescript-eslint/no-unsafe-enum-comparison': 'off',
    '@typescript-eslint/no-unsafe-member-access': 'off',
    '@typescript-eslint/no-unsafe-return': 'off',
    '@typescript-eslint/no-unused-expressions': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    '@typescript-eslint/prefer-destructuring': 'off',
    '@typescript-eslint/prefer-nullish-coalescing': 'off',
    '@typescript-eslint/prefer-optional-chain': 'off',
    '@typescript-eslint/require-await': 'off',
    '@typescript-eslint/switch-exhaustiveness-check': 'off',
    '@typescript-eslint/unbound-method': 'off',
    'default-case': 'off',
    'guard-for-in': 'off',
    'import/no-named-as-default': 'off',
    'max-depth': 'off',
    'max-lines': 'off',
    'max-lines-per-function': 'off',
    'new-cap': 'off',
    'no-await-in-loop': 'off',
    'no-console': 'off',
    'no-negated-condition': 'off',
    'no-param-reassign': 'off',
    'no-plusplus': 'off',
    'no-self-compare': 'off',
    'no-underscore-dangle': 'off',
    'no-useless-assignment': 'off',
    'prettier/prettier': 'off',
    'react-hooks/exhaustive-deps': 'off',
    'react-refresh/only-export-components': 'off',
    'require-atomic-updates': 'off',
  },
};

export default disabledRules;
