import { expect, type Locator, type Page } from '@playwright/test';

/**
 * Offload dropdown field identifiers matching the form field IDs
 * generated by getStorageMapFieldId(). The Select component uses
 * these as its `id` attribute.
 */
const OFFLOAD_FIELD = {
  offloadPlugin: (index: number): string => `storageMap.${index}.offloadPlugin`,
  storageProduct: (index: number): string => `storageMap.${index}.storageProduct`,
  storageSecret: (index: number): string => `storageMap.${index}.storageSecret`,
} as const;

const EXPANDABLE_TOGGLE_TEXT = 'Offload options (optional)';

/**
 * Page object for interacting with the offload options expandable section
 * in storage mapping rows. Works in create form, edit modal, and plan wizard.
 */
export class OffloadOptions {
  private readonly container: Locator;
  private readonly page: Page;

  /**
   * @param page - Playwright page
   * @param container - The parent container (e.g. modal locator, page body, wizard step)
   */
  constructor(page: Page, container?: Locator) {
    this.page = page;
    this.container = container ?? page.locator('body');
  }

  private expandableToggle(index: number): Locator {
    const allToggles = this.container.getByText(EXPANDABLE_TOGGLE_TEXT);
    return allToggles.nth(index);
  }

  private fieldToggleButton(fieldId: string): Locator {
    return this.container.getByTestId(fieldId);
  }

  private async isOffloadExpanded(mappingIndex: number): Promise<boolean> {
    return await this.fieldToggleButton(OFFLOAD_FIELD.offloadPlugin(mappingIndex)).isVisible();
  }

  private async selectFromDropdown(fieldId: string, optionText: string): Promise<void> {
    const toggle = this.fieldToggleButton(fieldId);
    await expect(toggle).toBeVisible();
    await toggle.click();

    const listbox = this.page.getByRole('listbox');
    await expect(listbox).toBeVisible();

    const option = listbox.getByRole('option', { name: optionText });
    await expect(option).toBeVisible();
    await option.click();
  }

  async collapseOffloadOptions(mappingIndex: number): Promise<void> {
    if (await this.isOffloadExpanded(mappingIndex)) {
      await this.expandableToggle(mappingIndex).click();
      await this.fieldToggleButton(OFFLOAD_FIELD.offloadPlugin(mappingIndex)).waitFor({
        state: 'hidden',
      });
    }
  }

  async expandOffloadOptions(mappingIndex: number): Promise<void> {
    if (!(await this.isOffloadExpanded(mappingIndex))) {
      const toggle = this.expandableToggle(mappingIndex);
      await expect(toggle).toBeVisible();
      await toggle.click();
    }
    await this.fieldToggleButton(OFFLOAD_FIELD.offloadPlugin(mappingIndex)).waitFor({
      state: 'visible',
    });
  }

  async getOffloadPluginText(mappingIndex: number): Promise<string> {
    const btn = this.fieldToggleButton(OFFLOAD_FIELD.offloadPlugin(mappingIndex));
    return ((await btn.textContent()) ?? '').trim();
  }

  async getStorageProductText(mappingIndex: number): Promise<string> {
    const btn = this.fieldToggleButton(OFFLOAD_FIELD.storageProduct(mappingIndex));
    return ((await btn.textContent()) ?? '').trim();
  }

  async getStorageSecretText(mappingIndex: number): Promise<string> {
    const btn = this.fieldToggleButton(OFFLOAD_FIELD.storageSecret(mappingIndex));
    return ((await btn.textContent()) ?? '').trim();
  }

  async selectOffloadPlugin(mappingIndex: number, optionText: string): Promise<void> {
    await this.selectFromDropdown(OFFLOAD_FIELD.offloadPlugin(mappingIndex), optionText);
  }

  async selectStorageProduct(mappingIndex: number, optionText: string): Promise<void> {
    await this.selectFromDropdown(OFFLOAD_FIELD.storageProduct(mappingIndex), optionText);
  }

  async selectStorageSecret(mappingIndex: number, secretName: string): Promise<void> {
    await this.selectFromDropdown(OFFLOAD_FIELD.storageSecret(mappingIndex), secretName);
  }

  async verifyAllDropdownsVisible(mappingIndex: number): Promise<void> {
    const pluginBtn = this.fieldToggleButton(OFFLOAD_FIELD.offloadPlugin(mappingIndex));
    const secretBtn = this.fieldToggleButton(OFFLOAD_FIELD.storageSecret(mappingIndex));
    const productBtn = this.fieldToggleButton(OFFLOAD_FIELD.storageProduct(mappingIndex));

    await expect(pluginBtn).toBeVisible();
    await expect(secretBtn).toBeVisible();
    await expect(productBtn).toBeVisible();
  }

  async verifyDropdownOptions(
    mappingIndex: number,
    field: 'offloadPlugin' | 'storageProduct' | 'storageSecret',
    expectedOptions: string[],
  ): Promise<void> {
    const fieldId = OFFLOAD_FIELD[field](mappingIndex);
    const toggle = this.fieldToggleButton(fieldId);

    await toggle.click();
    const listbox = this.page.getByRole('listbox');
    await listbox.waitFor({ state: 'visible' });

    const optionTexts = (await listbox.getByRole('option').allTextContents())
      .map((text) => text.trim())
      .filter(Boolean);

    for (const expected of expectedOptions) {
      expect(optionTexts).toContain(expected);
    }

    await toggle.click();
  }

  async verifyOffloadToggleNotVisible(mappingIndex: number): Promise<void> {
    await expect(this.expandableToggle(mappingIndex)).not.toBeVisible();
  }

  async verifyOffloadToggleVisible(mappingIndex: number): Promise<void> {
    const toggle = this.expandableToggle(mappingIndex);
    await expect(toggle).toBeVisible();
  }
}
