/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export * from './IoK8sApimachineryPkgApisMetaV1ObjectMeta';
export * from './V1beta1ForkliftController';
export * from './V1beta1Hook';
export * from './V1beta1Host';
export * from './V1beta1Migration';
export * from './V1beta1NetworkMap';
export * from './V1beta1NetworkMapStatusConditions';
export * from './V1beta1OvirtVolumePopulator';
export * from './V1beta1Plan';
export * from './V1beta1PlanStatusMigrationVms';
export * from './V1beta1Provider';
export * from './V1beta1ProviderStatus';
export * from './V1beta1ProviderStatusConditions';
export * from './V1beta1StorageMap';
export * from './V1beta1StorageMapStatusConditions';
