/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1PlanStatusMigrationHistoryMapNetwork } from './V1beta1PlanStatusMigrationHistoryMapNetwork';
import { V1beta1PlanStatusMigrationHistoryMapStorage } from './V1beta1PlanStatusMigrationHistoryMapStorage';

/**
 * Map.
 *
 * @export
 */
export interface V1beta1PlanStatusMigrationHistoryMap {
  /** network
   * Snapshot object reference.
   *
   * @required {false}
   */
  network?: V1beta1PlanStatusMigrationHistoryMapNetwork;
  /** storage
   * Snapshot object reference.
   *
   * @required {false}
   */
  storage?: V1beta1PlanStatusMigrationHistoryMapStorage;
}
