/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Source network.
 *
 * @export
 */
export interface V1beta1NetworkMapSpecMapSource {
  /** id
   * The object ID. vsphere: The managed object ID.
   *
   * @required {false}
   */
  id?: string;
  /** name
   * An object Name. vsphere: A qualified name.
   *
   * @required {false}
   */
  name?: string;
  /** namespace
   * Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
   *
   * @required {false}
   */
  namespace?: string;
  /** type
   * Type used to qualify the name.
   *
   * @required {false}
   */
  type?: string;
}
