/* tslint:disable */
/* eslint-disable */
/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact: kubev2v-dev@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * HostStatus defines the observed state of Host
 * @export
 * @interface V1beta1HostStatus
 */
export interface V1beta1HostStatus {
    /**
     * List of conditions.
     * @type {any}
     * @memberof V1beta1HostStatus
     */
    conditions?: any | null;
    /**
     * The most recent generation observed by the controller.
     * @type {any}
     * @memberof V1beta1HostStatus
     */
    observedGeneration?: any | null;
}

/**
 * Check if a given object implements the V1beta1HostStatus interface.
 */
export function instanceOfV1beta1HostStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1beta1HostStatusFromJSON(json: any): V1beta1HostStatus {
    return V1beta1HostStatusFromJSONTyped(json, false);
}

export function V1beta1HostStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1HostStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conditions': !exists(json, 'conditions') ? undefined : json['conditions'],
        'observedGeneration': !exists(json, 'observedGeneration') ? undefined : json['observedGeneration'],
    };
}

export function V1beta1HostStatusToJSON(value?: V1beta1HostStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conditions': value.conditions,
        'observedGeneration': value.observedGeneration,
    };
}

