/* tslint:disable */
/* eslint-disable */
/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact: kubev2v-dev@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1beta1OvirtVolumePopulatorSpec
 */
export interface V1beta1OvirtVolumePopulatorSpec {
    /**
     * 
     * @type {any}
     * @memberof V1beta1OvirtVolumePopulatorSpec
     */
    diskId: any | null;
    /**
     * 
     * @type {any}
     * @memberof V1beta1OvirtVolumePopulatorSpec
     */
    engineSecretName: any | null;
    /**
     * 
     * @type {any}
     * @memberof V1beta1OvirtVolumePopulatorSpec
     */
    engineUrl: any | null;
}

/**
 * Check if a given object implements the V1beta1OvirtVolumePopulatorSpec interface.
 */
export function instanceOfV1beta1OvirtVolumePopulatorSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "diskId" in value;
    isInstance = isInstance && "engineSecretName" in value;
    isInstance = isInstance && "engineUrl" in value;

    return isInstance;
}

export function V1beta1OvirtVolumePopulatorSpecFromJSON(json: any): V1beta1OvirtVolumePopulatorSpec {
    return V1beta1OvirtVolumePopulatorSpecFromJSONTyped(json, false);
}

export function V1beta1OvirtVolumePopulatorSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1OvirtVolumePopulatorSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'diskId': json['diskId'],
        'engineSecretName': json['engineSecretName'],
        'engineUrl': json['engineUrl'],
    };
}

export function V1beta1OvirtVolumePopulatorSpecToJSON(value?: V1beta1OvirtVolumePopulatorSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'diskId': value.diskId,
        'engineSecretName': value.engineSecretName,
        'engineUrl': value.engineUrl,
    };
}

