/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1HostSpecProvider } from './V1beta1HostSpecProvider';
import { V1beta1HostSpecSecret } from './V1beta1HostSpecSecret';

/**
 * HostSpec defines the desired state of Host
 *
 * @export
 */
export interface V1beta1HostSpec {
  /** id
   * The object ID. vsphere: The managed object ID.
   *
   * @required {false}
   */
  id?: string;
  /** ipAddress
   * IP address used for disk transfer.
   *
   * @required {true}
   */
  ipAddress: string;
  /** name
   * An object Name. vsphere: A qualified name.
   *
   * @required {false}
   */
  name?: string;
  /** provider
   * Provider
   *
   * @required {false}
   */
  provider?: V1beta1HostSpecProvider;
  /** secret
   * Credentials.
   *
   * @required {false}
   */
  secret?: V1beta1HostSpecSecret;
  /** thumbprint
   * Certificate SHA-1 fingerprint, called thumbprint by VMware.
   *
   * @required {false}
   */
  thumbprint?: string;
  /** type
   * Type used to qualify the name.
   *
   * @required {false}
   */
  type?: string;
}
