/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1NetworkMapSpecMap } from './V1beta1NetworkMapSpecMap';
import { V1beta1NetworkMapSpecProvider } from './V1beta1NetworkMapSpecProvider';

/**
 * Network map spec.
 *
 * @export
 */
export interface V1beta1NetworkMapSpec {
  /** map
   * Mapped network.
   *
   * @required {true}
   */
  map: V1beta1NetworkMapSpecMap[];
  /** provider
   * Provider
   *
   * @required {false}
   */
  provider?: V1beta1NetworkMapSpecProvider;
}
