/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1ProviderStatusConditions } from './V1beta1ProviderStatusConditions';

/**
 * ProviderStatus defines the observed state of Provider
 *
 * @export
 */
export interface V1beta1ProviderStatus {
  /** conditions
   * Condition
   *
   * @required {false}
   */
  conditions?: V1beta1ProviderStatusConditions[];
  /** observedGeneration
   * The most recent generation observed by the controller.
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  observedGeneration?: number;
  /** phase
   * Current life cycle phase of the provider.
   *
   * @required {false}
   */
  phase?: string;
}
