/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1NetworkMapSpecMapDestination } from './V1beta1NetworkMapSpecMapDestination';
import { V1beta1NetworkMapSpecMapSource } from './V1beta1NetworkMapSpecMapSource';

/**
 * Mapped network.
 *
 * @export
 */
export interface V1beta1NetworkMapSpecMap {
  /** destination
   * Destination network.
   *
   * @required {false}
   */
  destination?: V1beta1NetworkMapSpecMapDestination;
  /** source
   * Source network.
   *
   * @required {false}
   */
  source?: V1beta1NetworkMapSpecMapSource;
}
