/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1PlanStatusMigrationHistory } from './V1beta1PlanStatusMigrationHistory';
import { V1beta1PlanStatusMigrationVms } from './V1beta1PlanStatusMigrationVms';

/**
 * Migration
 *
 * @export
 */
export interface V1beta1PlanStatusMigration {
  /** completed
   * Completed timestamp.
   *
   * @required {false}
   * @format {date-time}
   */
  completed?: string;
  /** history
   * Snapshot
   *
   * @required {false}
   */
  history?: V1beta1PlanStatusMigrationHistory[];
  /** started
   * Started timestamp.
   *
   * @required {false}
   * @format {date-time}
   */
  started?: string;
  /** vms
   * VM Status
   *
   * @required {false}
   */
  vms?: V1beta1PlanStatusMigrationVms[];
}
