/* tslint:disable */
/* eslint-disable */
/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact: kubev2v-dev@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1beta1NetworkMapSpec } from './V1beta1NetworkMapSpec';
import {
    V1beta1NetworkMapSpecFromJSON,
    V1beta1NetworkMapSpecFromJSONTyped,
    V1beta1NetworkMapSpecToJSON,
} from './V1beta1NetworkMapSpec';
import type { V1beta1NetworkMapStatus } from './V1beta1NetworkMapStatus';
import {
    V1beta1NetworkMapStatusFromJSON,
    V1beta1NetworkMapStatusFromJSONTyped,
    V1beta1NetworkMapStatusToJSON,
} from './V1beta1NetworkMapStatus';

/**
 * 
 * @export
 * @interface V1beta1NetworkMap
 */
export interface V1beta1NetworkMap {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {any}
     * @memberof V1beta1NetworkMap
     */
    apiVersion?: any | null;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {any}
     * @memberof V1beta1NetworkMap
     */
    kind?: any | null;
    /**
     * 
     * @type {any}
     * @memberof V1beta1NetworkMap
     */
    metadata?: any | null;
    /**
     * 
     * @type {V1beta1NetworkMapSpec}
     * @memberof V1beta1NetworkMap
     */
    spec?: V1beta1NetworkMapSpec;
    /**
     * 
     * @type {V1beta1NetworkMapStatus}
     * @memberof V1beta1NetworkMap
     */
    status?: V1beta1NetworkMapStatus;
}

/**
 * Check if a given object implements the V1beta1NetworkMap interface.
 */
export function instanceOfV1beta1NetworkMap(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1beta1NetworkMapFromJSON(json: any): V1beta1NetworkMap {
    return V1beta1NetworkMapFromJSONTyped(json, false);
}

export function V1beta1NetworkMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1NetworkMap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'spec': !exists(json, 'spec') ? undefined : V1beta1NetworkMapSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : V1beta1NetworkMapStatusFromJSON(json['status']),
    };
}

export function V1beta1NetworkMapToJSON(value?: V1beta1NetworkMap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': value.metadata,
        'spec': V1beta1NetworkMapSpecToJSON(value.spec),
        'status': V1beta1NetworkMapStatusToJSON(value.status),
    };
}

