/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1PlanSpecVmsHooks } from './V1beta1PlanSpecVmsHooks';

/**
 * A VM listed on the plan.
 *
 * @export
 */
export interface V1beta1PlanSpecVms {
  /** hooks
   * Plan hook.
   *
   * @required {false}
   */
  hooks?: V1beta1PlanSpecVmsHooks[];
  /** id
   * The object ID. vsphere: The managed object ID.
   *
   * @required {false}
   */
  id?: string;
  /** name
   * An object Name. vsphere: A qualified name.
   *
   * @required {false}
   */
  name?: string;
  /** type
   * Type used to qualify the name.
   *
   * @required {false}
   */
  type?: string;
}
