/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface V1beta1OvirtVolumePopulatorSpec {
  /** diskId
   *
   * @required {true}
   */
  diskId: string;
  /** engineSecretName
   *
   * @required {true}
   */
  engineSecretName: string;
  /** engineUrl
   *
   * @required {true}
   */
  engineUrl: string;
}
