/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1StorageMapSpecProviderDestination } from './V1beta1StorageMapSpecProviderDestination';
import { V1beta1StorageMapSpecProviderSource } from './V1beta1StorageMapSpecProviderSource';

/**
 * Provider
 *
 * @export
 */
export interface V1beta1StorageMapSpecProvider {
  /** destination
   * Destination.
   *
   * @required {false}
   */
  destination?: V1beta1StorageMapSpecProviderDestination;
  /** source
   * Source.
   *
   * @required {false}
   */
  source?: V1beta1StorageMapSpecProviderSource;
}
