/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1MigrationStatusVmsWarmPrecopies } from './V1beta1MigrationStatusVmsWarmPrecopies';

/**
 * Warm migration status
 *
 * @export
 */
export interface V1beta1MigrationStatusVmsWarm {
  /** consecutiveFailures
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  consecutiveFailures: number;
  /** failures
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  failures: number;
  /** nextPrecopyAt
   *
   * @required {false}
   * @format {date-time}
   */
  nextPrecopyAt?: string;
  /** precopies
   * Precopy durations
   *
   * @required {false}
   */
  precopies?: V1beta1MigrationStatusVmsWarmPrecopies[];
  /** successes
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  successes: number;
}
