/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Errors
 *
 * @export
 */
export interface V1beta1MigrationStatusVmsError {
  /** phase
   *
   * @required {true}
   */
  phase: string;
  /** reasons
   *
   * @required {true}
   */
  reasons: string[];
}
