/* tslint:disable */
/* eslint-disable */
/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact: kubev2v-dev@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1beta1OvirtVolumePopulatorSpec } from './V1beta1OvirtVolumePopulatorSpec';
import {
    V1beta1OvirtVolumePopulatorSpecFromJSON,
    V1beta1OvirtVolumePopulatorSpecFromJSONTyped,
    V1beta1OvirtVolumePopulatorSpecToJSON,
} from './V1beta1OvirtVolumePopulatorSpec';
import type { V1beta1OvirtVolumePopulatorStatus } from './V1beta1OvirtVolumePopulatorStatus';
import {
    V1beta1OvirtVolumePopulatorStatusFromJSON,
    V1beta1OvirtVolumePopulatorStatusFromJSONTyped,
    V1beta1OvirtVolumePopulatorStatusToJSON,
} from './V1beta1OvirtVolumePopulatorStatus';

/**
 * 
 * @export
 * @interface V1beta1OvirtVolumePopulator
 */
export interface V1beta1OvirtVolumePopulator {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {any}
     * @memberof V1beta1OvirtVolumePopulator
     */
    apiVersion?: any | null;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {any}
     * @memberof V1beta1OvirtVolumePopulator
     */
    kind?: any | null;
    /**
     * 
     * @type {any}
     * @memberof V1beta1OvirtVolumePopulator
     */
    metadata?: any | null;
    /**
     * 
     * @type {V1beta1OvirtVolumePopulatorSpec}
     * @memberof V1beta1OvirtVolumePopulator
     */
    spec: V1beta1OvirtVolumePopulatorSpec;
    /**
     * 
     * @type {V1beta1OvirtVolumePopulatorStatus}
     * @memberof V1beta1OvirtVolumePopulator
     */
    status: V1beta1OvirtVolumePopulatorStatus;
}

/**
 * Check if a given object implements the V1beta1OvirtVolumePopulator interface.
 */
export function instanceOfV1beta1OvirtVolumePopulator(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "spec" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function V1beta1OvirtVolumePopulatorFromJSON(json: any): V1beta1OvirtVolumePopulator {
    return V1beta1OvirtVolumePopulatorFromJSONTyped(json, false);
}

export function V1beta1OvirtVolumePopulatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1OvirtVolumePopulator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'spec': V1beta1OvirtVolumePopulatorSpecFromJSON(json['spec']),
        'status': V1beta1OvirtVolumePopulatorStatusFromJSON(json['status']),
    };
}

export function V1beta1OvirtVolumePopulatorToJSON(value?: V1beta1OvirtVolumePopulator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': value.metadata,
        'spec': V1beta1OvirtVolumePopulatorSpecToJSON(value.spec),
        'status': V1beta1OvirtVolumePopulatorStatusToJSON(value.status),
    };
}

