/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1PlanStatusMigrationHistoryConditions } from './V1beta1PlanStatusMigrationHistoryConditions';
import { V1beta1PlanStatusMigrationHistoryMap } from './V1beta1PlanStatusMigrationHistoryMap';
import { V1beta1PlanStatusMigrationHistoryMigration } from './V1beta1PlanStatusMigrationHistoryMigration';
import { V1beta1PlanStatusMigrationHistoryPlan } from './V1beta1PlanStatusMigrationHistoryPlan';
import { V1beta1PlanStatusMigrationHistoryProvider } from './V1beta1PlanStatusMigrationHistoryProvider';

/**
 * Snapshot
 *
 * @export
 */
export interface V1beta1PlanStatusMigrationHistory {
  /** conditions
   * Condition
   *
   * @required {false}
   */
  conditions?: V1beta1PlanStatusMigrationHistoryConditions[];
  /** map
   * Map.
   *
   * @required {true}
   */
  map: V1beta1PlanStatusMigrationHistoryMap;
  /** migration
   * Migration
   *
   * @required {false}
   */
  migration?: V1beta1PlanStatusMigrationHistoryMigration;
  /** plan
   * Plan
   *
   * @required {false}
   */
  plan?: V1beta1PlanStatusMigrationHistoryPlan;
  /** provider
   * Provider
   *
   * @required {false}
   */
  provider?: V1beta1PlanStatusMigrationHistoryProvider;
}
