/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Hook specification.
 *
 * @export
 */
export interface V1beta1HookSpec {
  /** deadline
   * Hook deadline in seconds.
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  deadline?: number;
  /** image
   * Image to run.
   *
   * @required {true}
   */
  image: string;
  /** playbook
   * A base64 encoded Ansible playbook.
   *
   * @required {false}
   */
  playbook?: string;
  /** serviceAccount
   * Service account.
   *
   * @required {false}
   */
  serviceAccount?: string;
}
