/**
 * Forklift API
 * Migration toolkit for virtualization (Forklift) API definitions.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact Email: kubev2v-dev@redhat.com
 * License: Apache-2.0
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1ProviderSpecSecret } from './V1beta1ProviderSpecSecret';

/**
 * Defines the desired state of Provider.
 *
 * @export
 */
export interface V1beta1ProviderSpec {
  /** secret
   * References a secret containing credentials and other confidential information.
   *
   * @required {false}
   */
  secret?: V1beta1ProviderSpecSecret;
  /** settings
   * Provider settings.
   *
   * @required {false}
   * @originalType {not defined}
   */
  settings?: unknown | null;
  /** type
   * Provider type.
   *
   * @required {true}
   */
  type: string;
  /** url
   * The provider URL. Empty may be used for the `host` provider.
   *
   * @required {false}
   */
  url?: string;
}
