import { RESOURCE_KINDS, RESOURCE_TYPES } from './constants';

const RESOURCE_KIND_TO_TYPE: Record<string, string> = {
  [RESOURCE_KINDS.FORKLIFT_CONTROLLER]: RESOURCE_TYPES.FORKLIFT_CONTROLLERS,
  [RESOURCE_KINDS.MIGRATION]: RESOURCE_TYPES.MIGRATIONS,
  [RESOURCE_KINDS.NAMESPACE]: RESOURCE_TYPES.NAMESPACES,
  [RESOURCE_KINDS.NETWORK_ATTACHMENT_DEFINITION]: RESOURCE_TYPES.NETWORK_ATTACHMENT_DEFINITIONS,
  [RESOURCE_KINDS.NETWORK_MAP]: RESOURCE_TYPES.NETWORK_MAPS,
  [RESOURCE_KINDS.PLAN]: RESOURCE_TYPES.PLANS,
  [RESOURCE_KINDS.PROJECT]: RESOURCE_TYPES.PROJECTS,
  [RESOURCE_KINDS.PROVIDER]: RESOURCE_TYPES.PROVIDERS,
  [RESOURCE_KINDS.SECRET]: RESOURCE_TYPES.SECRETS,
  [RESOURCE_KINDS.STORAGE_MAP]: RESOURCE_TYPES.STORAGE_MAPS,
  [RESOURCE_KINDS.VIRTUAL_MACHINE]: RESOURCE_TYPES.VIRTUAL_MACHINES,
};

export const getResourceTypeFromKind = (kind: string): string => {
  return RESOURCE_KIND_TO_TYPE[kind] ?? `${kind.toLowerCase()}s`;
};
